### ISSUE TITLE
Create a README.md file

### ISSUE THREAD

**Issue by thomas-basham** [LChanthabandith/t.m.i.#3]
## [Use this template](https://github.com/CodeXAcademyTechnologies/springhill-code-201n1/blob/main/class-02/README-template.md) 

Be sure to link to the contributing file and any other resources that will help other devs to understand your project and be able to work on/maintain it.

**Comment by thomas-basham** [comment]
Also use this as a place to describe why you made the app and what it does, as well as any high level problems you solved, such as "the need for a simpler way to organize tasks"

**Comment by LChanthabandith** [comment]
I have successfully added the readme.md file to the repository. I used w3schools website heavily to refer and reference any code I needed better clarification on, especially when using JavaScript. I have linked HMTL, CSS, and JavaScript help forums and you can navigate the left side bar for code you are having trouble implementing.
