### ISSUE TITLE
Fix CSS import issue on deployed site

### ISSUE THREAD

**Issue by thomas-basham** [LChanthabandith/t.m.i.#4]
## Change this line 

            <link rel="stylesheet" type="text/css" href="/css/contact.css">
    
## To this 

            <link rel="stylesheet" type="text/css" href="css/contact.css">

**Comment by thomas-basham** [comment]
The `/` at the beginning of your file path is causing issues with importing that CSS file

**Comment by LChanthabandith** [comment]
Thank you! I did not realize the bug in my publish to GitHub pages because I assumed the file ran smoothly from my troubleshooting through my VS Code's live view. The issues has been fixed.

**Comment by thomas-basham** [comment]
Right on, will mark as resolved
